headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0",
    "Accept": "application/json",
    "authority": "api.mojidict.com",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
    "cache-control": "no-cache",
    "dnt": "1",
    "origin": "https://www.mojidict.com",
    "pragma": "no-cache",
    "referer": "https://www.mojidict.com/",
    "sec-ch-ua": '"Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
}

auth = {
    "_SessionToken": "r:88f5b47c28c4b0ad0763e256c8eeca92",
    "_ClientVersion": "js3.4.1",
    "_ApplicationId": "E62VyFVLMiW7kvbtVq3p",
    "g_os": "PCWeb",
    "g_ver": "v4.7.7.20240327",
    "_InstallationId": "8a92452c-5d64-4770-8e40-c647e61756ff",
}

anki_headers = {"Content-Type": "application/json"}

WORD_LIST_API = (
    "https://api.mojidict.com/parse/functions/folder-fetchContentWithRelatives"
)
WORD_DETAIL_BATCH_API = (
    "https://api.mojidict.com/parse/functions/nlt-fetchManyLatestWords"
)
WORD_DETAIL_API = "https://api.mojidict.com/parse/functions/web-word-fetchLatest"
WORD_VOICE_API = "https://api.mojidict.com/parse/functions/tts-fetch"
LOGIN_API = "https://api.mojidict.com/parse/functions/login"

DECK = {"deck_id": 1694497803948, "name": "日语"}

MODELS = {
    "model_id": 1709647089,
    "name": "みんなの日本語　単語",
    "fields": [
        {
            "name": "日文",
            "ord": 0,
            "sticky": True,
            "rtl": False,
            "font": "Source Han Serif JP",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "音调核",
            "ord": 1,
            "sticky": True,
            "rtl": False,
            "font": "Source Han Serif JP",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "词性",
            "ord": 2,
            "sticky": True,
            "rtl": False,
            "font": "Source Han Serif JP",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "基本形",
            "ord": 3,
            "sticky": False,
            "rtl": False,
            "font": "Source Han Serif JP",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "外来语",
            "ord": 4,
            "sticky": False,
            "rtl": False,
            "font": "思源宋体 CN",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "中文",
            "ord": 5,
            "sticky": False,
            "rtl": False,
            "font": "思源宋体 CN",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "音频",
            "ord": 6,
            "sticky": False,
            "rtl": False,
            "font": "Cascadia Code",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "是否需要从汉字到假名",
            "ord": 7,
            "sticky": False,
            "rtl": False,
            "font": "Cascadia Code",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "是否需要缩小日文",
            "ord": 8,
            "sticky": False,
            "rtl": False,
            "font": "Cascadia Code",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "是否需要缩小假名",
            "ord": 9,
            "sticky": False,
            "rtl": False,
            "font": "Cascadia Code",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
        {
            "name": "是否需要缩小中文",
            "ord": 10,
            "sticky": False,
            "rtl": False,
            "font": "Cascadia Code",
            "size": 20,
            "description": "",
            "plainText": False,
            "collapsed": False,
            "excludeFromSearch": False,
            "id": None,
            "tag": None,
            "preventDeletion": False,
        },
    ],
    "templates": [
        {
            "name": "音频",
            "ord": 0,
            "qfmt": '{{#是否需要从汉字到假名}}\n<div class="border kana">假名</div>\n<div class="basic_background section_main jp" style="display: flex; align-items: center;">\n    <span class="{{#是否需要缩小假名}}small{{/是否需要缩小假名}}" style="order: 1; flex: 1 1 auto;">\n        {{kana:日文}}\n        {{#基本形}}\n            <br/>\n            （←{{kana:基本形}}<span class="intonation">{{音调核}}</span>）\n        {{/基本形}}\n        {{^基本形}}\n            <span class="intonation">{{音调核}}</span>\n        {{/基本形}}\n    </span>\n    <span class="voice" style="order: 2;">{{音频}}</span>\n</div>\n{{/是否需要从汉字到假名}}',
            "afmt": '{{#是否需要从汉字到假名}}\n<div class="border kana">假名</div>\n<div class="basic_background section_main jp" style="display: flex; align-items: center;">\n    <span class="{{#是否需要缩小假名}}small{{/是否需要缩小假名}}" style="order: 1; flex: 1 1 auto;">\n        {{kana:日文}}\n        {{#基本形}}\n            <br/>\n            （←{{kana:基本形}}<span class="intonation">{{音调核}}</span>）\n        {{/基本形}}\n        {{^基本形}}\n            <span class="intonation">{{音调核}}</span>\n        {{/基本形}}\n    </span>\n    <span class="voice" style="order: 2;">{{音频}}</span>\n</div>\n{{/是否需要从汉字到假名}}\n\n<hr id=answer>\n\n<div class="border furigana">日文</div>\n<div class="basic_background section_info jp">\n    {{furigana:日文}}\n    {{#基本形}}\n        <br/>\n        （←{{furigana:基本形}}）\n    {{/基本形}}\n    {{#词性}}\n        <span class="word_type_interval"></span>\n        <span class="jp word_type">\n            〈{{词性}}〉\n        </span>\n    {{/词性}}\n</div>\n\n<div class="border chinese">中文</div>\n<div class="basic_background section_info">\n    <span>\n        {{中文}}\n    </span>\n    {{^是否需要从汉字到假名}}\n        {{#词性}}\n            <span class="word_type_interval"></span>\n            <span class="jp word_type">\n                〈{{词性}}〉\n            </span>\n        {{/词性}}\n    {{/是否需要从汉字到假名}}\n</div>\n\n{{#外来语}}\n<div class="border kana">外来语</div>\n<div class="basic_background section_info">\n    {{外来语}}\n</div>\n{{/外来语}}',
            "bqfmt": "",
            "bafmt": "",
            "did": None,
            "bfont": "",
            "bsize": 0,
            "id": None,
        },
        {
            "name": "日文",
            "ord": 1,
            "qfmt": '<div class="border furigana">日文</div>\n<div class="basic_background section_main jp" style="display: flex; align-items: center;">\n    <span class="{{#是否需要缩小日文}}small{{/是否需要缩小日文}}" style="order: 1; flex: 1 1 auto;">\n        {{#是否需要从汉字到假名}}\n            {{kanji:日文}}\n            {{#基本形}}\n                <br/>\n                （←{{kanji:基本形}}）\n            {{/基本形}}\n        {{/是否需要从汉字到假名}}\n        {{^是否需要从汉字到假名}}\n            {{furigana:日文}}\n            {{#基本形}}\n                <br/>\n                （←{{kanji:基本形}}<span class="intonation">{{音调核}}</span>）\n            {{/基本形}}\n            {{^基本形}}\n                <span class="intonation">{{音调核}}</span>\n            {{/基本形}}\n        {{/是否需要从汉字到假名}}\n    </span>\n    {{^是否需要从汉字到假名}}\n        <span class="voice" style="order: 2;">{{音频}}</span>\n    {{/是否需要从汉字到假名}}\n</div>',
            "afmt": '{{FrontSide}}\n\n<hr id=answer>\n\n{{#是否需要从汉字到假名}}\n<div class="border furigana">注音日文</div>\n<div class="basic_background section_info jp" style="display: flex; align-items: center;">\n    <span style="order: 1; flex: 1 1 auto;">\n        {{furigana:日文}}\n        {{#基本形}}\n            <br/>\n            （←{{furigana:基本形}}<span class="intonation">{{音调核}}</span>）\n        {{/基本形}}\n        {{^基本形}}\n            <span class="intonation">{{音调核}}</span>\n        {{/基本形}}\n        {{#词性}}\n            <span class="word_type_interval"></span>\n            <span class="jp word_type">\n                〈{{词性}}〉\n            </span>\n        {{/词性}}\n    </span>\n    <span class="voice" style="order: 2;">{{音频}}</span>\n</div>\n{{/是否需要从汉字到假名}}\n\n<div class="border chinese">中文</div>\n<div class="basic_background section_info">\n    {{中文}}\n    {{^是否需要从汉字到假名}}\n    {{#词性}}\n        <span class="word_type_interval"></span>\n        <span class="jp word_type">\n            〈{{词性}}〉\n        </span>\n    {{/词性}}\n    {{/是否需要从汉字到假名}}\n</div>\n\n{{#外来语}}\n<div class="border kana">外来语</div>\n<div class="basic_background section_info">\n    {{外来语}}\n</div>\n{{/外来语}}',
            "bqfmt": "",
            "bafmt": "",
            "did": None,
            "bfont": "",
            "bsize": 0,
            "id": None,
        },
        {
            "name": "中文",
            "ord": 2,
            "qfmt": '<div class="border chinese">中文</div>\n<div class="basic_background section_main" style="display: flex; align-items: center;">\n    <span id="chinese" class="small front">\n       {{中文}}\n    </span>\n</div>\n\n<script>\n  var chineseElement = document.getElementById(\'chinese\');\n  var chineseHTML = chineseElement.innerHTML;\n  \n  // 定义正则表达式匹配括号内的内容，假设它们出现在行的末尾 \n  var regex = /\\（[^）]+\\）(?=(<br>|<\\/div>|\\s*$))/g;\n  \n  // 将每行末尾的括号内容替换为空串，只留下中文解释\n  chineseElement.innerHTML = chineseHTML.replace(regex, \'\');\n</script>',
            "afmt": '<div class="border chinese">中文</div>\n<div class="basic_background section_main" style="display: flex; align-items: center;">\n    <span id="chinese" class="small">\n       {{中文}}\n    </span>\n</div>\n\n<hr id=answer>\n\n<div class="border furigana">日文</div>\n<div class="basic_background section_info jp" style="display: flex; align-items: center;">\n\t<span style="order: 1; flex: 1 1 auto;">\n\t\t{{furigana:日文}}\n        {{#基本形}}\n            <br/>\n            （←{{furigana:基本形}}<span class="intonation">{{音调核}}</span>）\n        {{/基本形}}\n        {{^基本形}}\n            <span class="intonation">{{音调核}}</span>\n        {{/基本形}}\n        {{#词性}}\n            <span class="word_type_interval"></span>\n            <span class="jp word_type">\n                〈{{词性}}〉\n            </span>\n        {{/词性}}\n\t</span>\n\t<span class="voice" style="order: 2;">{{音频}}</span>\n</div>\n\n{{#外来语}}\n<div class="border kana">外来语</div>\n<div class="basic_background section_info">\n    {{外来语}}\n</div>\n{{/外来语}}',
            "bqfmt": "",
            "bafmt": "",
            "did": None,
            "bfont": "",
            "bsize": 0,
            "id": None,
        },
    ],
    "css": "/* Font families */\n@font-face {\n    font-family: ChineseSerif;\n    src: url('_SourceHanSerifCN-Regular.otf');\n    font-display: swap;\n}\n\n@font-face {\n    font-family: JapaneseSerif;\n    src: url('_SourceHanSerifJP-Regular.otf');\n    font-display: swap;\n}\n\n.jp {\n    font-family: JapaneseSerif;\n}\n\n/* Card */\n.card {\n    font-family: ChineseSerif;\n    font-size: 24px;\n    text-align: center;\n    color: black;\n    background-color: white;\n}\n\n/* Utility */\n.unselectable {\n    -moz-user-select: none;\n    -o-user-select: none;\n    -khtml-user-select: none;\n    -webkit-user-select: none;\n    -ms-user-select: none;\n    user-select: none;\n}\n\n/* Classes for main matter. */\n.basic_background {\n    color: #222;\n    background-color: rgb(245, 245, 245);\n}\n.nightMode .basic_background {\n    color: #eee;\n    background-color: #444;\n}\n\n.section_main {\n    font-size: 45px;\n    text-align: left;\n    padding: 8px;\n}\n.section_main .small {\n    font-size: 25px;\n}\n.section_info {\n    text-align: left;\n    padding: 8px;\n    padding-left: 12px;\n}\n.intonation {\n    font-size: 28px;\n    vertical-align: middle;\n    white-space: nowrap;\n}\n.word_type_interval {\n    padding-right: 1em;\n}\n.word_type {\n    white-space: nowrap;\n}\n.voice {\n    font-size: 0px;\n}\n\n.border {\n    text-align: left;\n    font-size: 12px;\n    padding-left: 8px;\n}\n.kana {\n    color: #eee;\n    background-color: #888;\n}\n.furigana {\n    color: #666;\n    background-color: rgb(233, 233, 242);\n}\n.nightMode .furigana {\n    color: #666;\n    background-color: rgb(188, 188, 222);\n}\n.chinese {\n    color: #666;\n    background-color: rgb(242, 233, 233);\n}\n.nightMode .chinese {\n    color: #666;\n    background-color: rgb(222, 188, 188);\n}\n\n.front .jptext {\n    display: none; /* 在正面隐藏日语解释 */\n  }\n\n",
}
